version: '3.1'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456 
      - PGDATA= /data/postgres
      - POSTGRES_DB=devs
    volumes:
      - postgres:/data/postgres
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=biricikserhat47@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5000:80
   
    
    volumes:
      - pgadmin-data:/var/lib/pgadmin




volumes:
    postgres:
    pgadmin-data: