# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: kodlama.io-devs

on:
  push:
    branches: [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven export jar
      run: mvn -B package --file pom.xml
      
      
    
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # username
        username: ${{secrets.USERNAME}}
        # your sftp server
        server:  ${{secrets.IP}}
        # you can copy private_key from your *.pem file, keep format
        ssh_private_key: ${{secrets.SSH}}
        # will put all file under this path
        local_path: ./target/devs-0.0.1-SNAPSHOT.jar
        # files will copy to under remote_path
        remote_path: /home/biricikserhat47
        
        
        
    - name: SSH REMOTE COMMANDS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host:  ${{secrets.IP}}
        username: ${{secrets.USERNAME}}
        key:  ${{secrets.SSH}}
        script: |
          cd /home/biricikserhat47
          pkill -u biricikserhat47 'java'
          nohup java -jar  -Djava.security.edg=file:/dev/./urandom devs-0.0.1-SNAPSHOT.jar  > /dev/null 2>&1 &
        
        

        
   
   
    
     
          
        
     



      


 
